# Generated by Django 4.2.3 on 2023-07-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blogapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publication_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
